name: rem-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.8
  - datashader=0.13
  - geopandas
  - matplotlib
  - notebook=6.4
  - numpy
  - osmnx=1.1
  - pandas
  - rioxarray=0.10
  - scipy=1.8
  - shapely
  - xarray-spatial=0.3
  - xarray=0.21
