name: rem-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.8
  - datashader
  - geopandas
  - matplotlib
  - notebook
  - numpy
  - osmnx
  - pandas
  - rioxarray
  - scipy
  - shapely
  - xarray-spatial
  - xarray
