name: rem-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.8
  - datashader
  - geopandas
  - matplotlib
  - notebook=6.4
  - numpy
  - osmnx=1.1
  - pandas
  - rioxarray
  - scipy
  - shapely
  - xarray-spatial=0.3
  - xarray=0.21
